name: Auto-merge Copilot PRs

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: github.actor == 'Antboi123'
    steps:
      - name: Auto-merge
        uses: pascalgn/automerge-action@v0.16.3
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          merge_method: "squash"
